name: Spectrum Heritage

# Build settings
markdown: kramdown
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', 'README.md', 'LICENSE']
plugins:
  - jekyll-sitemap
  - kramdown

