source 'https://rubygems.org'
ruby '2.4.0'
gem 'github-pages', '161', group: :jekyll_plugins
gem 'jekyll', '~> 3.5'
gem 'jekyll-sitemap'
gem 'kramdown', '1.13.2'
gem 'rack-jekyll', '~> 0.5'
gem 'rake', '12.1.0'
gem 'puma', '3.10.0'
gem 'yajl-ruby', '~> 1.3.1'
