source 'https://rubygems.org'
ruby '2.4.0'
gem 'github-pages', group: :jekyll_plugins
gem 'jekyll', '~> 3.5'
gem 'jekyll-sitemap'
gem 'kramdown', '1.13.2'
gem 'rack-jekyll', '0.5.0'
gem 'rake', '12.0.0'
gem 'puma', '3.7.1'
gem 'yajl-ruby', '1.3.0'
